# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
    adapter: mysql2
    username: root
    password: password
    host: localhost
    encoding: utf8
    database: memoreal_development

test:
    adapter: mysql2
    username: root
    password: password
    host: localhost
    encoding: utf8
    database: memoreal_test

test:
    adapter: mysql2
    username: root
    password: password
    host: localhost
    encoding: utf8
    database: memoreal
